name = "make-a-pick"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "out"
main = "./index.js"

# Pages configuration
pages_build_output_dir = "out"

# Environment variables (add your own as needed)
[vars]
# NODE_ENV = "production"
# Add other environment variables here

# KV Namespaces (if needed for future features)
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 Database (if needed for future features)
# [[d1_databases]]
# binding = "DB"
# database_name = "make-a-pick-db"
# database_id = "your-database-id"

# R2 Bucket (if needed for file storage)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "make-a-pick-assets"

# Analytics Engine (if needed for analytics)
# [[analytics_engine_datasets]]
# binding = "AE"
# dataset = "make-a-pick-analytics"